j=252;
i=useTrials(j);
params.tapers=[5 9];
params.Fs=1000;
params.trialave=1;
params.fpass=[3 16];

% x=linspace(0,5,size(popTrials.trialINCFar(i,:),2));
% figure(); plot(downSampAv(x,20),downSampAv(nanmean([popTrials.trialINC(i,:); popTrials.trialDEC(i,:)],1),20));
% xlim([4 5]);
% temp=downSampMatrix(popTrials.trialINCFar(i,:),20);
% xtemp=downSampAv(x,20);
% figure(); plot(xtemp,bandPassLFP(nanmean(temp,1),50,8,12,0),'Color','k');
% xlim([4 5]);
% x=linspace(0,5,size(popTrials.trialDECFar(i,:),2));
% temp2=downSampMatrix(popTrials.trialDECFar(i,:),20);
% xtemp=downSampAv(x,20);
% hold on; plot(xtemp,bandPassLFP(nanmean(temp2,1),50,8,12,0),'Color','r');
% xlim([4 5]);
% figure(); plot(xtemp,bandPassLFP(nanmean(temp,1),50,8,12,0)-bandPassLFP(nanmean(temp2,1),50,8,12,0),'Color','b');
% xlim([4 5]);

x=linspace(0,5,size(popTrials.trialINCFar(i,:),2));
figure(); plot(downSampAv(x,20),downSampAv(nanmean([popTrials.trialINC(i,:); popTrials.trialDEC(i,:)],1),20));
xlim([3.5 5]);
temp=downSampMatrix(popTrials.trialINCFar(i,:),20);
xtemp=downSampAv(x,20);
figure(); plot(xtemp,bandPassLFP(nanmean(temp,1),50,4,12,0),'Color','k');
xlim([3.5 5]);
[S,f]=mtspectrumpb(popTrials.trialINCFar(i,x>=4 & x<=5)',params);
x=linspace(0,5,size(popTrials.trialDECFar(i,:),2));
temp2=downSampMatrix(popTrials.trialDECFar(i,:),20);
xtemp=downSampAv(x,20);
hold on; plot(xtemp,bandPassLFP(nanmean(temp2,1),50,4,12,0),'Color','r');
xlim([3.5 5]);
figure(); plot(xtemp,bandPassLFP(nanmean(temp,1),50,4,12,0)-bandPassLFP(nanmean(temp2,1),50,4,12,0),'Color','b');
xlim([3.5 5]);
[Sdec,fdec]=mtspectrumpb(popTrials.trialDECFar(i,x>=4 & x<=5)',params);
figure(); plot(f,S-mean(S),'Color','k'); hold on;
plot(fdec,Sdec-mean(Sdec),'Color','r');